apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: resource-topology-exporter-v2
allowHostDirVolumePlugin: true
fsGroup:
  type: RunAsAny
readOnlyRootFilesystem: false
runAsUser:
  type: RunAsAny
seLinuxContext:
  seLinuxOptions:
    level: s0
    type: container_device_plugin_t
  type: MustRunAs
supplementalGroups:
  type: RunAsAny
users: []
volumes:
- configMap
- downwardAPI
- emptyDir
- hostPath
- projected
- secret
