apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: topology-aware-scheduler-egress-to-api-server
spec:
  podSelector:
    matchLabels:
      component: scheduler
  egress:
  - ports:
    - protocol: TCP
      port: 6443 
  policyTypes:
  - Egress