apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: topology-aware-scheduler-default-deny-all
spec:
  podSelector:
    matchLabels:
      component: scheduler
  policyTypes:
  - Ingress
  - Egress
