apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: topology-aware-controller-default-deny-all
spec:
  podSelector:
    matchLabels:
      app: topology-aware-controller
  policyTypes:
  - Ingress
  - Egress
